import React,{createContext,useContext,useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,Routes,Route,Link,Navigate,useNavigate}from'react-router-dom';import{Landmark,CreditCard,WalletCards,ShieldCheck,LogOut}from'lucide-react';import'./style.css';
const Auth=createContext();const api=async(path,opt={})=>{const token=localStorage.getItem('token');const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...opt.headers}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Request failed');return d};
function AuthProvider({children}){const[user,setUser]=useState(null);const[loading,setLoading]=useState(true);useEffect(()=>{localStorage.getItem('token')?api('/users/me').then(setUser).catch(()=>localStorage.removeItem('token')).finally(()=>setLoading(false)):setLoading(false)},[]);const login=async(x)=>{const d=await api('/auth/login',{method:'POST',body:JSON.stringify(x)});localStorage.setItem('token',d.token);setUser(d.user)};const register=async(x)=>{const d=await api('/auth/register',{method:'POST',body:JSON.stringify(x)});localStorage.setItem('token',d.token);setUser(d.user)};const logout=()=>{localStorage.removeItem('token');setUser(null)};return <Auth.Provider value={{user,loading,login,register,logout}}>{children}</Auth.Provider>}
const features=[['Savings Account','Simple savings with account overview and transactions.'],['Personal Account','View and update your profile and contact details.'],['Cards','Apply for debit, credit, and virtual cards.'],['Services','Payments, recharge, deposits, and customer support.']];
function Nav(){const{user,logout}=useContext(Auth);return <nav><Link className="brand" to="/"><Landmark/> Digital Bank</Link><div><Link to="/">Home</Link>{user?<><Link to="/dashboard">Dashboard</Link><Link to="/accounts">Savings</Link><Link to="/cards">Cards</Link><Link to="/services">Services</Link><button className="link" onClick={logout}><LogOut size={16}/>Logout</button></>:<><Link to="/login">Login</Link><Link className="pill" to="/register">Register</Link></>}</div></nav>}
function Home(){return <><section className="hero"><div><span className="badge">Secure. Simple. Digital.</span><h1>Banking designed around your life.</h1><p>Manage savings, cards, transactions, and everyday services from one responsive portal.</p><Link className="cta" to="/register">Open an account</Link></div><div className="bank-card"><small>DIGITAL BANK</small><b>•••• •••• •••• 2048</b><span>YOUR NAME</span></div></section><section className="grid">{features.map(([a,b])=><article key={a}><ShieldCheck/><h3>{a}</h3><p>{b}</p></article>)}</section></>}
function Login(){const{login}=useContext(Auth),nav=useNavigate();const[e,setE]=useState('');const submit=async ev=>{ev.preventDefault();try{await login(Object.fromEntries(new FormData(ev.currentTarget)));nav('/dashboard')}catch(x){setE(x.message)}};return <Form title="Welcome back" submit={submit} error={e}><input name="login" placeholder="Email or username" required/><input name="password" type="password" placeholder="Password" required/><button>Sign in</button></Form>}
function Register(){const{register}=useContext(Auth),nav=useNavigate();const[e,setE]=useState('');const submit=async ev=>{ev.preventDefault();try{await register(Object.fromEntries(new FormData(ev.currentTarget)));nav('/dashboard')}catch(x){setE(x.message)}};return <Form title="Create your account" submit={submit} error={e} wide>{['fullName:Full name','email:Email','phone:Phone','username:Username','dateOfBirth:Date of birth','address:Address','city:City','state:State','pinCode:PIN code','occupation:Occupation','annualIncome:Annual income'].map(x=>{const[n,p]=x.split(':');return <input key={n} name={n} type={n==='email'?'email':n==='dateOfBirth'?'date':n==='annualIncome'?'number':'text'} placeholder={p} required={['fullName','email','phone','username'].includes(n)}/>})}<select name="gender"><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><input name="identityNumber" placeholder="Identity number (only last 4 retained)"/><input name="password" type="password" placeholder="Password: upper, lower, number, 8+ chars" required/><button>Create account</button></Form>}
function Form({title,submit,error,children,wide}){return <main className={'formbox '+(wide?'wide':'')}><h2>{title}</h2>{error&&<p className="error">{error}</p>}<form onSubmit={submit}>{children}</form></main>}
function Protected({children}){const{user,loading}=useContext(Auth);return loading?<p>Loading...</p>:user?children:<Navigate to="/login"/>}
function Dashboard(){const{user}=useContext(Auth);const[accounts,setAccounts]=useState([]),[tx,setTx]=useState([]);useEffect(()=>{api('/accounts').then(setAccounts);api('/transactions').then(setTx)},[]);return <main><h2>Hello, {user.fullName}</h2><div className="stats"><article><WalletCards/><small>Available balance</small><strong>₹{Number(accounts[0]?.balance||0).toLocaleString()}</strong></article><article><CreditCard/><small>Account number</small><strong>{accounts[0]?.accountNumber||'Creating...'}</strong></article></div><h3>Recent transactions</h3><List items={tx.map(x=>`${x.type.toUpperCase()} · ₹${x.amount} · ${x.status}`)}/></main>}
function Accounts(){const[a,setA]=useState([]),[e,setE]=useState('');const load=()=>api('/accounts').then(setA);useEffect(load,[]);const submit=async ev=>{ev.preventDefault();try{await api('/transactions',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))});setE('Transaction completed');ev.currentTarget.reset();load()}catch(x){setE(x.message)}};return <main><h2>Savings Account</h2>{a.map(x=><article className="account" key={x.id}><b>{x.accountNumber}</b><strong>₹{Number(x.balance).toLocaleString()}</strong><span>{x.status}</span></article>)}<Form title="Demo transaction" submit={submit} error={e}><select name="type"><option value="deposit">Deposit</option><option value="withdrawal">Withdraw</option></select><input name="amount" type="number" min="1" step="0.01" placeholder="Amount" required/><input name="description" placeholder="Description"/><button>Submit</button></Form></main>}
function Cards(){const[c,setC]=useState([]);const load=()=>api('/cards').then(setC);useEffect(load,[]);const add=async()=>{await api('/cards',{method:'POST',body:JSON.stringify({type:'debit'})});load()};const toggle=async id=>{await api(`/cards/${id}/toggle`,{method:'PATCH'});load()};return <main><h2>Cards</h2><button onClick={add}>Apply for debit card</button><div className="grid">{c.map(x=><article key={x.id}><CreditCard/><h3>{x.maskedNumber}</h3><p>{x.type} · expires {x.expiry}</p><button onClick={()=>toggle(x.id)}>{x.status==='active'?'Freeze':'Unfreeze'}</button></article>)}</div></main>}
function Services(){const[s,setS]=useState([]);useEffect(()=>{api('/services').then(setS)},[]);return <main><h2>Banking Services</h2><div className="grid">{s.map(x=><article key={x}><h3>{x}</h3><p>Service interface ready for the next business workflow.</p></article>)}</div></main>}
const List=({items})=><div className="list">{items.length?items.map((x,i)=><div key={i}>{x}</div>):<p>No records yet.</p>}</div>;
function App(){return <AuthProvider><Nav/><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/accounts" element={<Protected><Accounts/></Protected>}/><Route path="/cards" element={<Protected><Cards/></Protected>}/><Route path="/services" element={<Protected><Services/></Protected>}/></Routes><footer>Digital Bank Training Application</footer></AuthProvider>};createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
